# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/axb-mac/dev/cpp/zindex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/axb-mac/dev/cpp/zindex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.18.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/axb-mac/dev/cpp/zindex/CMakeFiles /Users/axb-mac/dev/cpp/zindex//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/axb-mac/dev/cpp/zindex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libzindex

# Build rule for target.
libzindex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libzindex
.PHONY : libzindex

# fast build rule for target.
libzindex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/build
.PHONY : libzindex/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named zq

# Build rule for target.
zq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zq
.PHONY : zq

# fast build rule for target.
zq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq.dir/build.make CMakeFiles/zq.dir/build
.PHONY : zq/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named zindex

# Build rule for target.
zindex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zindex
.PHONY : zindex

# fast build rule for target.
zindex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zindex.dir/build.make CMakeFiles/zindex.dir/build
.PHONY : zindex/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

ext/cJSON/cJSON.o: ext/cJSON/cJSON.c.o

.PHONY : ext/cJSON/cJSON.o

# target to build an object file
ext/cJSON/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/cJSON/cJSON.c.o
.PHONY : ext/cJSON/cJSON.c.o

ext/cJSON/cJSON.i: ext/cJSON/cJSON.c.i

.PHONY : ext/cJSON/cJSON.i

# target to preprocess a source file
ext/cJSON/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/cJSON/cJSON.c.i
.PHONY : ext/cJSON/cJSON.c.i

ext/cJSON/cJSON.s: ext/cJSON/cJSON.c.s

.PHONY : ext/cJSON/cJSON.s

# target to generate assembly for a file
ext/cJSON/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/cJSON/cJSON.c.s
.PHONY : ext/cJSON/cJSON.c.s

ext/sqlite/sqlite3.o: ext/sqlite/sqlite3.c.o

.PHONY : ext/sqlite/sqlite3.o

# target to build an object file
ext/sqlite/sqlite3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/sqlite/sqlite3.c.o
.PHONY : ext/sqlite/sqlite3.c.o

ext/sqlite/sqlite3.i: ext/sqlite/sqlite3.c.i

.PHONY : ext/sqlite/sqlite3.i

# target to preprocess a source file
ext/sqlite/sqlite3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/sqlite/sqlite3.c.i
.PHONY : ext/sqlite/sqlite3.c.i

ext/sqlite/sqlite3.s: ext/sqlite/sqlite3.c.s

.PHONY : ext/sqlite/sqlite3.s

# target to generate assembly for a file
ext/sqlite/sqlite3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/ext/sqlite/sqlite3.c.s
.PHONY : ext/sqlite/sqlite3.c.s

src/ConsoleLog.o: src/ConsoleLog.cpp.o

.PHONY : src/ConsoleLog.o

# target to build an object file
src/ConsoleLog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/ConsoleLog.cpp.o
.PHONY : src/ConsoleLog.cpp.o

src/ConsoleLog.i: src/ConsoleLog.cpp.i

.PHONY : src/ConsoleLog.i

# target to preprocess a source file
src/ConsoleLog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/ConsoleLog.cpp.i
.PHONY : src/ConsoleLog.cpp.i

src/ConsoleLog.s: src/ConsoleLog.cpp.s

.PHONY : src/ConsoleLog.s

# target to generate assembly for a file
src/ConsoleLog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/ConsoleLog.cpp.s
.PHONY : src/ConsoleLog.cpp.s

src/FieldIndexer.o: src/FieldIndexer.cpp.o

.PHONY : src/FieldIndexer.o

# target to build an object file
src/FieldIndexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/FieldIndexer.cpp.o
.PHONY : src/FieldIndexer.cpp.o

src/FieldIndexer.i: src/FieldIndexer.cpp.i

.PHONY : src/FieldIndexer.i

# target to preprocess a source file
src/FieldIndexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/FieldIndexer.cpp.i
.PHONY : src/FieldIndexer.cpp.i

src/FieldIndexer.s: src/FieldIndexer.cpp.s

.PHONY : src/FieldIndexer.s

# target to generate assembly for a file
src/FieldIndexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/FieldIndexer.cpp.s
.PHONY : src/FieldIndexer.cpp.s

src/Index.o: src/Index.cpp.o

.PHONY : src/Index.o

# target to build an object file
src/Index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Index.cpp.o
.PHONY : src/Index.cpp.o

src/Index.i: src/Index.cpp.i

.PHONY : src/Index.i

# target to preprocess a source file
src/Index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Index.cpp.i
.PHONY : src/Index.cpp.i

src/Index.s: src/Index.cpp.s

.PHONY : src/Index.s

# target to generate assembly for a file
src/Index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Index.cpp.s
.PHONY : src/Index.cpp.s

src/IndexParser.o: src/IndexParser.cpp.o

.PHONY : src/IndexParser.o

# target to build an object file
src/IndexParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/IndexParser.cpp.o
.PHONY : src/IndexParser.cpp.o

src/IndexParser.i: src/IndexParser.cpp.i

.PHONY : src/IndexParser.i

# target to preprocess a source file
src/IndexParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/IndexParser.cpp.i
.PHONY : src/IndexParser.cpp.i

src/IndexParser.s: src/IndexParser.cpp.s

.PHONY : src/IndexParser.s

# target to generate assembly for a file
src/IndexParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/IndexParser.cpp.s
.PHONY : src/IndexParser.cpp.s

src/LineFinder.o: src/LineFinder.cpp.o

.PHONY : src/LineFinder.o

# target to build an object file
src/LineFinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/LineFinder.cpp.o
.PHONY : src/LineFinder.cpp.o

src/LineFinder.i: src/LineFinder.cpp.i

.PHONY : src/LineFinder.i

# target to preprocess a source file
src/LineFinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/LineFinder.cpp.i
.PHONY : src/LineFinder.cpp.i

src/LineFinder.s: src/LineFinder.cpp.s

.PHONY : src/LineFinder.s

# target to generate assembly for a file
src/LineFinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/LineFinder.cpp.s
.PHONY : src/LineFinder.cpp.s

src/Pipe.o: src/Pipe.cpp.o

.PHONY : src/Pipe.o

# target to build an object file
src/Pipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Pipe.cpp.o
.PHONY : src/Pipe.cpp.o

src/Pipe.i: src/Pipe.cpp.i

.PHONY : src/Pipe.i

# target to preprocess a source file
src/Pipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Pipe.cpp.i
.PHONY : src/Pipe.cpp.i

src/Pipe.s: src/Pipe.cpp.s

.PHONY : src/Pipe.s

# target to generate assembly for a file
src/Pipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Pipe.cpp.s
.PHONY : src/Pipe.cpp.s

src/PrettyBytes.o: src/PrettyBytes.cpp.o

.PHONY : src/PrettyBytes.o

# target to build an object file
src/PrettyBytes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/PrettyBytes.cpp.o
.PHONY : src/PrettyBytes.cpp.o

src/PrettyBytes.i: src/PrettyBytes.cpp.i

.PHONY : src/PrettyBytes.i

# target to preprocess a source file
src/PrettyBytes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/PrettyBytes.cpp.i
.PHONY : src/PrettyBytes.cpp.i

src/PrettyBytes.s: src/PrettyBytes.cpp.s

.PHONY : src/PrettyBytes.s

# target to generate assembly for a file
src/PrettyBytes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/PrettyBytes.cpp.s
.PHONY : src/PrettyBytes.cpp.s

src/RangeFetcher.o: src/RangeFetcher.cpp.o

.PHONY : src/RangeFetcher.o

# target to build an object file
src/RangeFetcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RangeFetcher.cpp.o
.PHONY : src/RangeFetcher.cpp.o

src/RangeFetcher.i: src/RangeFetcher.cpp.i

.PHONY : src/RangeFetcher.i

# target to preprocess a source file
src/RangeFetcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RangeFetcher.cpp.i
.PHONY : src/RangeFetcher.cpp.i

src/RangeFetcher.s: src/RangeFetcher.cpp.s

.PHONY : src/RangeFetcher.s

# target to generate assembly for a file
src/RangeFetcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RangeFetcher.cpp.s
.PHONY : src/RangeFetcher.cpp.s

src/RegExp.o: src/RegExp.cpp.o

.PHONY : src/RegExp.o

# target to build an object file
src/RegExp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RegExp.cpp.o
.PHONY : src/RegExp.cpp.o

src/RegExp.i: src/RegExp.cpp.i

.PHONY : src/RegExp.i

# target to preprocess a source file
src/RegExp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RegExp.cpp.i
.PHONY : src/RegExp.cpp.i

src/RegExp.s: src/RegExp.cpp.s

.PHONY : src/RegExp.s

# target to generate assembly for a file
src/RegExp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/RegExp.cpp.s
.PHONY : src/RegExp.cpp.s

src/Sqlite.o: src/Sqlite.cpp.o

.PHONY : src/Sqlite.o

# target to build an object file
src/Sqlite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Sqlite.cpp.o
.PHONY : src/Sqlite.cpp.o

src/Sqlite.i: src/Sqlite.cpp.i

.PHONY : src/Sqlite.i

# target to preprocess a source file
src/Sqlite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Sqlite.cpp.i
.PHONY : src/Sqlite.cpp.i

src/Sqlite.s: src/Sqlite.cpp.s

.PHONY : src/Sqlite.s

# target to generate assembly for a file
src/Sqlite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/Sqlite.cpp.s
.PHONY : src/Sqlite.cpp.s

src/StringView.o: src/StringView.cpp.o

.PHONY : src/StringView.o

# target to build an object file
src/StringView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/StringView.cpp.o
.PHONY : src/StringView.cpp.o

src/StringView.i: src/StringView.cpp.i

.PHONY : src/StringView.i

# target to preprocess a source file
src/StringView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/StringView.cpp.i
.PHONY : src/StringView.cpp.i

src/StringView.s: src/StringView.cpp.s

.PHONY : src/StringView.s

# target to generate assembly for a file
src/StringView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libzindex.dir/build.make CMakeFiles/libzindex.dir/src/StringView.cpp.s
.PHONY : src/StringView.cpp.s

src/zindex.o: src/zindex.cpp.o

.PHONY : src/zindex.o

# target to build an object file
src/zindex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zindex.dir/build.make CMakeFiles/zindex.dir/src/zindex.cpp.o
.PHONY : src/zindex.cpp.o

src/zindex.i: src/zindex.cpp.i

.PHONY : src/zindex.i

# target to preprocess a source file
src/zindex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zindex.dir/build.make CMakeFiles/zindex.dir/src/zindex.cpp.i
.PHONY : src/zindex.cpp.i

src/zindex.s: src/zindex.cpp.s

.PHONY : src/zindex.s

# target to generate assembly for a file
src/zindex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zindex.dir/build.make CMakeFiles/zindex.dir/src/zindex.cpp.s
.PHONY : src/zindex.cpp.s

src/zq.o: src/zq.cpp.o

.PHONY : src/zq.o

# target to build an object file
src/zq.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq.dir/build.make CMakeFiles/zq.dir/src/zq.cpp.o
.PHONY : src/zq.cpp.o

src/zq.i: src/zq.cpp.i

.PHONY : src/zq.i

# target to preprocess a source file
src/zq.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq.dir/build.make CMakeFiles/zq.dir/src/zq.cpp.i
.PHONY : src/zq.cpp.i

src/zq.s: src/zq.cpp.s

.PHONY : src/zq.s

# target to generate assembly for a file
src/zq.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zq.dir/build.make CMakeFiles/zq.dir/src/zq.cpp.s
.PHONY : src/zq.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... libzindex"
	@echo "... zindex"
	@echo "... zq"
	@echo "... ext/cJSON/cJSON.o"
	@echo "... ext/cJSON/cJSON.i"
	@echo "... ext/cJSON/cJSON.s"
	@echo "... ext/sqlite/sqlite3.o"
	@echo "... ext/sqlite/sqlite3.i"
	@echo "... ext/sqlite/sqlite3.s"
	@echo "... src/ConsoleLog.o"
	@echo "... src/ConsoleLog.i"
	@echo "... src/ConsoleLog.s"
	@echo "... src/FieldIndexer.o"
	@echo "... src/FieldIndexer.i"
	@echo "... src/FieldIndexer.s"
	@echo "... src/Index.o"
	@echo "... src/Index.i"
	@echo "... src/Index.s"
	@echo "... src/IndexParser.o"
	@echo "... src/IndexParser.i"
	@echo "... src/IndexParser.s"
	@echo "... src/LineFinder.o"
	@echo "... src/LineFinder.i"
	@echo "... src/LineFinder.s"
	@echo "... src/Pipe.o"
	@echo "... src/Pipe.i"
	@echo "... src/Pipe.s"
	@echo "... src/PrettyBytes.o"
	@echo "... src/PrettyBytes.i"
	@echo "... src/PrettyBytes.s"
	@echo "... src/RangeFetcher.o"
	@echo "... src/RangeFetcher.i"
	@echo "... src/RangeFetcher.s"
	@echo "... src/RegExp.o"
	@echo "... src/RegExp.i"
	@echo "... src/RegExp.s"
	@echo "... src/Sqlite.o"
	@echo "... src/Sqlite.i"
	@echo "... src/Sqlite.s"
	@echo "... src/StringView.o"
	@echo "... src/StringView.i"
	@echo "... src/StringView.s"
	@echo "... src/zindex.o"
	@echo "... src/zindex.i"
	@echo "... src/zindex.s"
	@echo "... src/zq.o"
	@echo "... src/zq.i"
	@echo "... src/zq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

