name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        config:
          - name: "default"
            cmake_flags: ""
          - name: "static"
            cmake_flags: "-DStatic=ON"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake zlib1g-dev
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew update
        brew install cmake zlib
        
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake .. ${{ matrix.config.cmake_flags }}
        make -j4
        
    - name: Package artifacts
      run: |
        mkdir -p release
        cp build/zindex build/zq release/
        tar czvf zq-${{ github.ref_name }}-${{ matrix.os }}.tar.gz -C release .
        
    - name: Run basic tests
      run: |
        cd build
        ./zq --help
        ./zindex --help
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: ./zq-${{ github.ref_name }}-${{ matrix.os }}.tar.gz